### 
# MkDocs Configuration File.
# 
# To build these docs, change to base of repository and run `mkdocs build` and
# docs will be build into site_dir variable value in this file.
# 
# Alternatively, there is a script in the `scripts` folder for convenience.
### 
site_name: fpdf2
site_url: https://pyfpdf.github.io/fpdf2/
repo_url: https://github.com/PyFPDF/fpdf2
site_description: fpdf2 - minimalist PDF creation library for Python
docs_dir: docs/
site_dir: public/
use_directory_urls: false
edit_uri: edit/master/docs
theme:
  name: material
  custom_dir: docs/overrides/
markdown_extensions: [toc, pymdownx.highlight, pymdownx.superfences]
plugins:
  - include-markdown
  - search
  - with-pdf:  # https://github.com/orzih/mkdocs-with-pdf
      output_path: fpdf2-manual.pdf
      cover_title: fpdf2 manual
      cover_subtitle: A minimalist PDF creation library for Python
      author: ' '
      copyright: ' '
      #cover: false
      #back_cover: true
      #custom_template_path: TEMPLATES PATH
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #exclude_pages:
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #two_columns_level: 3
      #render_js: true
      #headless_chrome_path: headless-chromium
      #enabled_if_env: ENABLE_PDF_EXPORT
      #debug_html: true
      #show_anchors: true
      #verbose: true
nav:
- 'Project Home':                   'index.md'
- 'Tutorial':
  - 'Tutorial in english':            'Tutorial.md'
  - 'Tutorial auf Deutsch':           'Tutorial-de.md'
  - 'Tutorial en español':            'Tutorial-es.md'
  - 'Tutorial en français':           'Tutorial-fr.md'
  - 'Tutorial in italiano':           'Tutorial-it.md'
  - 'Tutorial em português':          'Tutorial-pt.md'
  - 'Учебник на русском языке':       'Tutorial-ru.md'
  - 'हिंदी में ट्यूटोरिय':                     'Tutorial-हिंदी.md'
- 'Page Layout':
  - 'Page Format and Orientation':    'PageFormatAndOrientation.md'
  - 'Margins':                        'Margins.md'
  - 'Templates':                      'Templates.md'
  - 'Tables':                         'Tables.md'
- 'Text Content':
  - 'Adding Text':                    'Text.md'
  - 'Line breaks':                    'LineBreaks.md'
  - 'Page breaks':                    'PageBreaks.md'
  - 'Text styling':                   'TextStyling.md'
  - 'Unicode':                        'Unicode.md'
  - 'Emojis, Symbols & Dingbats':     'EmojisSymbolsDingbats.md'
  - 'HTML':                           'HTML.md'
- 'Graphics Content':
  - 'Images':                         'Images.md'
  - 'Shapes':                         'Shapes.md'
  - 'Transparency':                   'Transparency.md'
  - 'Barcodes':                       'Barcodes.md'
  - 'Drawing':                        'Drawing.md'
  - 'SVG':                            'SVG.md'
  - 'Charts & Graphs':                'Maths.md'
- 'PDF Features':
  - 'Links':                          'Links.md'
  - 'Metadata':                       'Metadata.md'
  - 'Annotations':                    'Annotations.md'
  - 'Presentation Mode':              'Presentations.md'
  - 'Document outline & table of contents': 'DocumentOutlineAndTableOfContents.md'
  - 'Signing':                        'Signing.md'
- 'Mixing other libs':
  - 'Existing PDFs':                  'ExistingPDFs.md'
  - 'Usage in web APIs':              'UsageInWebAPI.md'
  - 'Database storage':               'DatabaseStorage.md'
  - 'borb':                           'borb.md'
- 'Development':
  - 'Development Guidelines':         'Development.md'
  - 'Logging':                        'Logging.md'
- 'API':                            'https://pyfpdf.github.io/fpdf2/fpdf/'
- 'FAQ':                            'FAQ.md'
