### 
# MkDocs Configuration File.
# 
# To build these docs, change to base of repository and run `mkdocs build` and
# docs will be build into site_dir variable value in this file.
# 
# Alternatively, there is a script in the `scripts` folder for convenience.
### 
site_name: fpdf2
site_url: https://pyfpdf.github.io/fpdf2/
repo_url: https://github.com/PyFPDF/fpdf2
site_description: fpdf2 - minimalist PDF creation library for Python
docs_dir: docs/
site_dir: public/
use_directory_urls: false
edit_uri: edit/master/docs
theme:
  name: material
  custom_dir: docs/overrides/
markdown_extensions: [toc, pymdownx.highlight, pymdownx.superfences]
plugins:
  - include-markdown
nav:
- 'Project Home':                   'index.md'
- 'Tutorial':                       'Tutorial.md'
- 'Existing PDFs':                  'ExistingPDFs.md'
- 'HTML':                           'HTML.md'
- 'Images':                         'Images.md'
- 'Links':                          'Links.md'
- 'Tables':                         'Tables.md'
- 'Layout':
  - 'Page format and orientation':  'PageFormatAndOrientation.md'
  - 'Margins':                      'Margins.md'
  - 'Page breaks':                  'PageBreaks.md'
- 'Document outline & table of contents': 'DocumentOutlineAndTableOfContents.md'
- 'Text styling':                   'TextStyling.md'
- 'Presentations':                  'Presentations.md'
- 'Annotations':                    'Annotations.md'
- 'Shapes':                         'Shapes.md'
- 'Maths':                          'Maths.md'
- 'Barcodes':                       'Barcodes.md'
- 'Metadata':                       'Metadata.md'
- 'Logging':                        'Logging.md'
- 'Templates':                      'Templates.md'
- 'Unicode':                        'Unicode.md'
- 'Web2Py':                         'Web2Py.md'
- 'API':                            'https://pyfpdf.github.io/fpdf2/fpdf/'
- 'Development':                    'Development.md'
- 'FAQ':                            'FAQ.md'
